name: virtualpilgrimage
description: healthcare app to enjoy Shikoku Pilgrimage

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.4+7

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  # firebase
  # core以外のバージョンを指定しないことでcoreに依存したバージョンがインストールされる
  # 2022/11現在、coreの2系は安定していないらしいので、1系の最新を導入
  firebase_core: ^1.24.0
  firebase_core_platform_interface: 4.5.1
  firebase_analytics:
  firebase_auth:
  cloud_firestore:
  firebase_crashlytics:
  firebase_storage:

  # utilities
  flutter_riverpod: ^2.1.1
  go_router: ^5.1.5
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.4.1
  sign_in_with_apple: ^4.2.0
  logger: ^1.1.0
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  intl: ^0.17.0
  http: ^0.13.5
  image_picker: ^0.8.6
  maps_toolkit: ^2.0.1
  package_info: ^2.0.2
  url_launcher: ^6.1.7
  webview_flutter: ^4.0.5

  # ui
  google_maps_flutter: ^2.2.1
  google_polyline_algorithm: ^3.1.0
  flutter_toggle_tab: ^1.2.0
  percent_indicator: ^4.2.2
  settings_ui: ^2.0.2
  flutter_native_splash: ^2.2.19
  google_fonts: any
  
  # health
  health: ^4.4.0
  permission_handler: ^9.2.0 # Firebaseと同じSDKをターゲットにできるよう最新ではないバージョンを利用

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  freezed: ^2.3.2
  mockito: ^5.3.2
  network_image_mock: ^2.1.1

  flutter_launcher_icons: ^0.12.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/icon512.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/icon256_adaptive.png'

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/images/icon768_for_splash.png'
  fullscreen: true
  android_12:
    icon_background_color: '#ffffff'
    image: 'assets/images/icon768_1192_for_splash_android12.png'
